-- Insertar algunos países asociados a los continentes
INSERT INTO wonderfull_travel.ofertes (pais_id, preu, imatges, durada_dies, valida)
VALUES (1, 111, "./source/optimizadas/africa/kenia/kenia_peq.webp", 3, 1),
    (2, 222, "./source/optimizadas/africa/nigeria/nigeria_peq.webp", 3, 1),
    (3, 333, "./source/optimizadas/africa/sudán/sudán_peq.webp", 3, 1),
    (4, 444, "./source/optimizadas/africa/botswana/botswana_peq.webp", 3, 1),
    (5, 555, "./source/optimizadas/africa/burkina_faso/burkina_faso_peq.webp", 3, 1),
    (6, 666, "./source/optimizadas/asia/china/china_peq.webp", 3, 1),
    (7, 777, "./source/optimizadas/asia/rusia/rusia_peq.webp", 3, 1),
    (8, 888, "./source/optimizadas/asia/india/india_peq.webp", 3, 1),
    (9, 999, "./source/optimizadas/asia/bangladesh/bangladesh_peq.webp", 3, 1),
    (10, 111, "./source/optimizadas/asia/pakistan/pakistan_peq.webp", 3, 1),
    (11, 222, "./source/optimizadas/europa/españa/españa_peq.webp", 3, 1),
    (12, 333, "./source/optimizadas/europa/holanda/holanda_peq.webp", 3, 1),
    (13, 444, "./source/optimizadas/europa/italia/italia_peq.webp", 3, 1),
    (14, 555, "./source/optimizadas/europa/croacia/croacia_peq.webp", 3, 1),
    (15, 666, "./source/optimizadas/europa/chipre/chipre_peq.webp", 3, 1),
    (16, 777, "./source/optimizadas/america_norte/canada/canada_peq.webp", 3, 1),
    (17, 888, "./source/optimizadas/america_norte/estados_unidos/estados_unidos_peq.webp", 3, 1),
    (18, 999, "./source/optimizadas/america_norte/mexico/mexico_peq.webp", 3, 1),
    (19, 111, "./source/optimizadas/america_norte/barbados/barbados_peq.webp", 3, 1),
    (20, 222, "./source/optimizadas/america_norte/belize/belize_peq.webp", 3, 1),
    (21, 333, "./source/optimizadas/oceania/australia/australia_peq.webp", 3, 1),
    (22, 444, "./source/optimizadas/oceania/fiji/fiji_peq.webp", 3, 1),
    (23, 555, "./source/optimizadas/oceania/nueva_zelanda/nueva_zelanda_peq.webp", 3, 1),
    (24, 666, "./source/optimizadas/oceania/marshall_islands/marshall_islands_peq.webp", 3, 1),
    (25, 777, "./source/optimizadas/oceania/micronesia/micronesia_peq.webp", 3, 1),
    (26, 888, "./source/optimizadas/america_sur/brazil/brazil_peq.webp", 3, 1),
    (27, 999, "./source/optimizadas/america_sur/argentina/argentina_peq.webp", 3, 1),
    (28, 111, "./source/optimizadas/america_sur/bolivia/bolivia_peq.webp", 3, 1),
    (29, 222, "./source/optimizadas/america_sur/perú/perú_peq.webp", 3, 1),
    (30, 333, "./source/optimizadas/america_sur/colombia/colombia_peq.webp", 3, 1);