-- Insertar algunos continentes y obtener sus IDs
INSERT INTO wonderfull_travel.continent (nom) VALUES
    ('Africa'),
    ('Asia'),
    ('Europa'),
    ('Nord América'),
    ('Oceania'),
    ('Sud América');

-- Obtener los IDs de los continentes recién insertados
SET @idAfrica = LAST_INSERT_ID();
SET @idAsia = @idAfrica + 1;
SET @idEuropa = @idAsia + 1;
SET @idNordAmerica = @idEuropa + 1;
SET @idOceania = @idNordAmerica + 1;
SET @idSudAmerica = @idOceania + 1;


-- Insertar algunos países asociados a los continentes
INSERT INTO wonderfull_travel.pais (continent_id, nom) VALUES
(@idEuropa, "Andorra"),
(@idAsia, "United Arab Emirates"),
(@idAsia, "Afghanistan"),
(@idNordAmerica, "Antigua and Barbuda"),
(@idNordAmerica, "Anguilla"),
(@idEuropa, "Albania"),
(@idAsia, "Armenia"),
(@idNordAmerica, "Netherlands Antilles"),
(@idAfrica, "Angola"),
(@idSudAmerica, "Argentina"),
(@idOceania, "American Samoa"),
(@idEuropa, "Austria"),
(@idOceania, "Australia"),
(@idNordAmerica, "Aruba"),
(@idEuropa, "Åland"),
(@idAsia, "Azerbaijan"),
(@idEuropa, "Bosnia and Herzegovina"),
(@idNordAmerica, "Barbados"),
(@idAsia, "Bangladesh"),
(@idEuropa, "Belgium"),
(@idAfrica, "Burkina Faso"),
(@idEuropa, "Bulgaria"),
(@idAsia, "Bahrain"),
(@idAfrica, "Burundi"),
(@idAfrica, "Benin"),
(@idNordAmerica, "Saint Barthélemy"),
(@idNordAmerica, "Bermuda"),
(@idAsia, "Brunei Darussalam"),
(@idSudAmerica, "Bolivia"),
(@idSudAmerica, "Brazil"),
(@idNordAmerica, "Bahamas"),
(@idAsia, "Bhutan"),
(@idAfrica, "Botswana"),
(@idEuropa, "Belarus"),
(@idNordAmerica, "Belize"),
(@idNordAmerica, "Canada"),
(@idAsia, "Cocos (Keeling) Islands"),
(@idAfrica, "Congo (Kinshasa)"),
(@idAfrica, "Central African Republic"),
(@idAfrica, "Congo (Brazzaville)"),
(@idEuropa, "Switzerland"),
(@idAfrica, "Côte d\'Ivoire"),
(@idOceania, "Cook Islands"),
(@idSudAmerica, "Chile"),
(@idAfrica, "Cameroon"),
(@idAsia, "China"),
(@idSudAmerica, "Colombia"),
(@idNordAmerica, "Costa Rica"),
(@idNordAmerica, "Cuba"),
(@idAfrica, "Cape Verde"),
(@idAsia, "Christmas Island"),
(@idAsia, "Cyprus"),
(@idEuropa, "Czech Republic"),
(@idEuropa, "Germany"),
(@idAfrica, "Djibouti"),
(@idEuropa, "Denmark"),
(@idNordAmerica, "Dominica"),
(@idNordAmerica, "Dominican Republic"),
(@idAfrica, "Algeria"),
(@idSudAmerica, "Ecuador"),
(@idEuropa, "Estonia"),
(@idAfrica, "Egypt"),
(@idAfrica, "Western Sahara"),
(@idAfrica, "Eritrea"),
(@idEuropa, "Spain"),
(@idAfrica, "Ethiopia"),
(@idEuropa, "Finland"),
(@idOceania, "Fiji"),
(@idSudAmerica, "Falkland Islands"),
(@idOceania, "Micronesia"),
(@idEuropa, "Faroe Islands"),
(@idEuropa, "France"),
(@idAfrica, "Gabon"),
(@idEuropa, "United Kingdom"),
(@idNordAmerica, "Grenada"),
(@idAsia, "Georgia"),
(@idSudAmerica, "French Guiana"),
(@idEuropa, "Guernsey"),
(@idAfrica, "Ghana"),
(@idEuropa, "Gibraltar"),
(@idNordAmerica, "Greenland"),
(@idAfrica, "Gambia"),
(@idAfrica, "Guinea"),
(@idNordAmerica, "Guadeloupe"),
(@idAfrica, "Equatorial Guinea"),
(@idEuropa, "Greece"),
(@idNordAmerica, "Guatemala"),
(@idOceania, "Guam"),
(@idAfrica, "Guinea-Bissau"),
(@idSudAmerica, "Guyana"),
(@idAsia, "Hong Kong"),
(@idNordAmerica, "Honduras"),
(@idEuropa, "Croatia"),
(@idNordAmerica, "Haiti"),
(@idEuropa, "Hungary"),
(@idAsia, "Indonesia"),
(@idEuropa, "Ireland"),
(@idAsia, "Israel"),
(@idEuropa, "Isle of Man"),
(@idAsia, "India"),
(@idAsia, "British Indian Ocean Territory"),
(@idAsia, "Iraq"),
(@idAsia, "Iran"),
(@idEuropa, "Iceland"),
(@idEuropa, "Italy"),
(@idEuropa, "Jersey"),
(@idNordAmerica, "Jamaica"),
(@idAsia, "Jordan"),
(@idAsia, "Japan"),
(@idAfrica, "Kenya"),
(@idAsia, "Kyrgyzstan"),
(@idAsia, "Cambodia"),
(@idOceania, "Kiribati"),
(@idAfrica, "Comoros"),
(@idNordAmerica, "Saint Kitts and Nevis"),
(@idAsia, "Korea, North"),
(@idAsia, "Korea, South"),
(@idAsia, "Kuwait"),
(@idNordAmerica, "Cayman Islands"),
(@idAsia, "Kazakhstan"),
(@idAsia, "Laos"),
(@idAsia, "Lebanon"),
(@idNordAmerica, "Saint Lucia"),
(@idEuropa, "Liechtenstein"),
(@idAsia, "Sri Lanka"),
(@idAfrica, "Liberia"),
(@idAfrica, "Lesotho"),
(@idEuropa, "Lithuania"),
(@idEuropa, "Luxembourg"),
(@idEuropa, "Latvia"),
(@idAfrica, "Libya"),
(@idAfrica, "Morocco"),
(@idEuropa, "Monaco"),
(@idEuropa, "Moldova"),
(@idEuropa, "Montenegro"),
(@idNordAmerica, "Saint Martin (French part)"),
(@idAfrica, "Madagascar"),
(@idOceania, "Marshall Islands"),
(@idEuropa, "Macedonia"),
(@idAfrica, "Mali"),
(@idAsia, "Myanmar"),
(@idAsia, "Mongolia"),
(@idAsia, "Macau"),
(@idOceania, "Northern Mariana Islands"),
(@idNordAmerica, "Martinique"),
(@idAfrica, "Mauritania"),
(@idNordAmerica, "Montserrat"),
(@idEuropa, "Malta"),
(@idAfrica, "Mauritius"),
(@idAsia, "Maldives"),
(@idAfrica, "Malawi"),
(@idNordAmerica, "Mexico"),
(@idAsia, "Malaysia"),
(@idAfrica, "Mozambique"),
(@idAfrica, "Namibia"),
(@idOceania, "New Caledonia"),
(@idAfrica, "Niger"),
(@idOceania, "Norfolk Island"),
(@idAfrica, "Nigeria"),
(@idNordAmerica, "Nicaragua"),
(@idEuropa, "Netherlands"),
(@idEuropa, "Norway"),
(@idAsia, "Nepal"),
(@idOceania, "Nauru"),
(@idOceania, "Niue"),
(@idOceania, "New Zealand"),
(@idAsia, "Oman"),
(@idNordAmerica, "Panama"),
(@idSudAmerica, "Peru"),
(@idOceania, "French Polynesia"),
(@idOceania, "Papua New Guinea"),
(@idAsia, "Philippines"),
(@idAsia, "Pakistan"),
(@idEuropa, "Poland"),
(@idNordAmerica, "Saint Pierre and Miquelon"),
(@idOceania, "Pitcairn"),
(@idNordAmerica, "Puerto Rico"),
(@idAsia, "Palestine"),
(@idEuropa, "Portugal"),
(@idOceania, "Palau"),
(@idSudAmerica, "Paraguay"),
(@idAsia, "Qatar"),
(@idAfrica, "Reunion"),
(@idEuropa, "Romania"),
(@idEuropa, "Serbia"),
(@idEuropa, "Russian Federation"),
(@idAfrica, "Rwanda"),
(@idAsia, "Saudi Arabia"),
(@idOceania, "Solomon Islands"),
(@idAfrica, "Seychelles"),
(@idAfrica, "Sudan"),
(@idEuropa, "Sweden"),
(@idAsia, "Singapore"),
(@idAfrica, "Saint Helena"),
(@idEuropa, "Slovenia"),
(@idEuropa, "Svalbard and Jan Mayen Islands"),
(@idEuropa, "Slovakia"),
(@idAfrica, "Sierra Leone"),
(@idEuropa, "San Marino"),
(@idAfrica, "Senegal"),
(@idAfrica, "Somalia"),
(@idSudAmerica, "Suriname"),
(@idAfrica, "Sao Tome and Principe"),
(@idNordAmerica, "El Salvador"),
(@idAsia, "Syria"),
(@idAfrica, "Swaziland"),
(@idNordAmerica, "Turks and Caicos Islands"),
(@idAfrica, "Chad"),
(@idAfrica, "Togo"),
(@idAsia, "Thailand"),
(@idAsia, "Tajikistan"),
(@idOceania, "Tokelau"),
(@idAsia, "Timor-Leste"),
(@idAsia, "Turkmenistan"),
(@idAfrica, "Tunisia"),
(@idOceania, "Tonga"),
(@idAsia, "Turkey"),
(@idNordAmerica, "Trinidad and Tobago"),
(@idOceania, "Tuvalu"),
(@idAsia, "Taiwan"),
(@idAfrica, "Tanzania"),
(@idEuropa, "Ukraine"),
(@idAfrica, "Uganda"),
(@idOceania, "United States Minor Outlying Islands"),
(@idNordAmerica, "United States of America"),
(@idSudAmerica, "Uruguay"),
(@idAsia, "Uzbekistan"),
(@idEuropa, "Vatican City"),
(@idNordAmerica, "Saint Vincent and the Grenadines"),
(@idSudAmerica, "Venezuela"),
(@idNordAmerica, "Virgin Islands, British"),
(@idNordAmerica, "Virgin Islands, U.S."),
(@idAsia, "Vietnam"),
(@idOceania, "Vanuatu"),
(@idOceania, "Wallis and Futuna Islands"),
(@idOceania, "Samoa"),
(@idAsia, "Yemen"),
(@idAfrica, "Mayotte"),
(@idAfrica, "South Africa"),
(@idAfrica, "Zambia"),
(@idAfrica, "Zimbabwe");